export const S = {
  title: 'Penguen Şef',
  subtitle: 'Doğru yemek, doğru müşteriye!',
  play: 'Oyna',
  playAgain: 'Tekrar Oyna',
  resume: 'Devam',
  restart: 'Baştan Başla',
  mainMenu: 'Ana Menü',
  paused: 'Duraklatıldı',
  howTo: [
    'Yemekler banttan aşağı kayar.',
    '◀ sola ya da ▶ sağa dokun: en öndeki yemek o müşteriye gider.',
    'Kimse istemiyorsa bırak, çöpe düşsün.',
  ],
  keysHint: 'Klavye: ← →  ·  P duraklat  ·  M ses',
  tapToStart: 'Başlamak için dokun',
  left: 'SOL',
  right: 'SAĞ',

  newDish: (n) => `Yeni yemek: ${n}!`,
  level: (n) => `SEVİYE ${n}`,
  levelUp: 'Bant hızlanıyor!',
  combo: (m) => `Kombo x${m}`,
  wrong: 'Bu değil!',
  angry: 'Gitti!',
  heal: '+1 kalp',
  vip: 'VIP',

  resultTitle: 'El Bitti!',
  score: 'Skor',
  served: 'Servis edilen',
  bestCombo: 'En uzun kombo',
  time: 'Süre',
  reachedLevel: 'Ulaşılan seviye',
  bestSession: 'Bu oturumdaki en iyi',
};
